### ISSUE TITLE
Last update more than 2 years ago, is this alive or dead?

### ISSUE THREAD

**Issue by sauliusm** [Bokun/bokun_api#1]
Is the api client still up to date and usable? 

Or would we be better off implementing our own client based on the docs?

**Comment by ogg** [comment]
We have moved away from maintaining API clients for our API. Instead, we maintain an OpenAPI (Swagger) documentation of our API online:  https://bokun.github.io/api-docs/ 

You can then generate a client in your preferred language using the Swagger editor: http://editor.swagger.io/#/?import=https://bokun.github.io/api-docs/bokun.yaml 

It is very simple, just click Generate Client, and select the type of client you would like:

<img width="938" alt="screen shot 2017-02-20 at 14 00 52" src="https://cloud.githubusercontent.com/assets/241700/23128121/a22312a0-f775-11e6-99c5-b20ba1777bbb.png">
